# This file should get deleted upon project instantiation, but it may get left
# behind by legacy kobweb binaries. Feel free to remove it if you're seeing this!

metadata:
  name: "site"
  description: "A template for a minimal site that demonstrates the basic features of Kobweb"
  shouldHighlight: true

instructions:
  # Note: Kobweb provides a "projectFolder" variable for us already

  - !<QueryVar>
    name: "projectTitle"
    prompt: "What is the user-visible display title for your project?"
    default: "${fileToTitle(projectFolder)}"
    validation: "isNotEmpty"
  - !<DefineVar>
    name: "projectName"
    value: "${fileToPackage(projectFolder)}"
  - !<Inform>
    message: "Note: The group ID should uniquely identify your project and organization."
  - !<Inform>
    message: "'io.github.(username).(projectname)' can work for a hobby project."
  - !<QueryVar>
    name: "groupId"
    prompt: "What is the group ID for your project?"
    default: "org.example.${projectName}"
    validation: "isPackage"
  # Overwrite projectName, since the user's group ID should be a more accurate indication
  # of what the user wants their project name to be than the initial folder.
  - !<DefineVar>
    name: "projectName"
    value: "${groupId?keep_after_last(\".\")}"
  # Copy "groupId" as "package" -- it reads better in some cases.
  - !<DefineVar>
    name: "package"
    value: "${groupId}"

  - !<ProcessFreemarker>

  - !<DefineVar>
    name: "packagePath"
    value: "${packageToPath(package)}"
  - !<Move>
    from: "src/site/*"
    to: "src/jsMain/kotlin/${packagePath}"
    description: "Copying frontend code"
  - !<Move>
    from: "src/api/*"
    to: "src/jvmMain/kotlin/${packagePath}/api"
    description: "Copying backend code"
  - !<Move>
    from: "resources/*"
    to: "src/jsMain/resources"
    description: "Copying resources"
