# This file should get deleted upon project instantiation, but it may get left
# behind by legacy kobweb binaries. Feel free to remove it if you're seeing this!

metadata:
  description: "A very minimal site with just a counter (based on the Jetbrains tutorial)"

# No need for any instructions - we just copy the demo as is

