# This file should get deleted upon project instantiation, but it may get left
# behind by legacy kobweb binaries. Feel free to remove it if you're seeing this!

metadata:
  description: "An example TODO app, showcasing client / server interactions"

# No need for any instructions - we just copy the demo as is

